# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app.kubernetes.io/name: django-todo
#     app.kubernetes.io/managed-by: kubectl
#   name: django-todo
# spec:
#   selector:
#     app: django-todo
#   type: LoadBalancer
#   ports:
#    -  protocol: TCP
#       port: 8000
#       targetPort: 8000
#       nodePort: 32100
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000